#include "../chard.h"

void usage(const char *prog) {
    fprintf(stderr,
        "usage: %s -c <input.ch> [-o <output.s>] [-target=x86-64|aarch64|riscv]\n"
        "  -c <input.ch>   source file to compile (required)\n"
        "  -o <output.s>     output path (default: derived from input, .ch -> .s)\n"
        "  -target=<name>    x86-64 | aarch64 (alias: arm64) | riscv\n"
        "                    (default: host's native architecture)\n"
        "\n"
        "File extensions (conventional, not enforced):\n"
        "  .ch   ordinary source -- compile directly, or '| include' from another file\n"
        "  .chh  header/library -- '| include' only (macros/structs/enums/equs)\n"
        "  .chd  data -- '| data' only (volatile/bss/data declarations)\n"
        "\n"
        "Tip: chain several instructions on one line with ':' or ';;' instead of\n"
        "giving each its own line, e.g. 'mv r1 > r2 : mv r2 > r3 : exit(0);'\n"
        "or 'mv r1 > r2 ;; mv r2 > r3 ;; exit(0);'\n",
        prog);
}

target_t detect_native_target(void) {
#if defined(__aarch64__) || defined(__arm64__)
    return TARGET_AARCH64;
#elif defined(__riscv)
    return TARGET_RISCV;
#elif defined(__x86_64__) || defined(_M_X64)
    return TARGET_X86_64;
#else
    return TARGET_X86_64; /* fallback: unrecognized host, guess x86-64 */
#endif
}

char *derive_output_path(const char *input_path) {
    size_t len = strlen(input_path);
    const char *base = strrchr(input_path, '/');
    base = base ? base + 1 : input_path;

    const char *dot = strrchr(base, '.');
    size_t stem_len = dot ? (size_t)(dot - input_path) : len;

    char *out = malloc(stem_len + 3 /* ".s" + NUL */);
    if (!out) { perror("malloc"); exit(1); }
    memcpy(out, input_path, stem_len);
    out[stem_len] = '\0';
    strcat(out, ".s");
    return out;
}

char *derive_ld_script_path(const char *output_path) {
    size_t len = strlen(output_path);
    const char *base = strrchr(output_path, '/');
    base = base ? base + 1 : output_path;

    const char *dot = strrchr(base, '.');
    size_t stem_len = dot ? (size_t)(dot - output_path) : len;

    char *out = malloc(stem_len + 4 /* ".ld" + NUL */);
    if (!out) { perror("malloc"); exit(1); }
    memcpy(out, output_path, stem_len);
    out[stem_len] = '\0';
    strcat(out, ".ld");
    return out;
}

void write_bare_mode_linker_script(const char *ld_path) {
    FILE *ld = fopen(ld_path, "w");
    if (!ld) { perror("fopen linker script"); exit(1); }

    fprintf(ld, "/* Generated by chard alongside its .s output -- see\n");
    fprintf(ld, "   write_bare_mode_linker_script's comment in chard.c for why\n");
    fprintf(ld, "   this file exists. Usage:\n");
    fprintf(ld, "     as <output.s> -o <output.o>\n");
    fprintf(ld, "     ld -T %s <output.o> -o <output.elf>\n", ld_path);
    fprintf(ld, "     objcopy -O binary <output.elf> <output.bin>\n");
    fprintf(ld, "   <output.bin> is then the flat image, loaded starting at\n");
    fprintf(ld, "   0x%lx (Chard's '| foot' address), matching what NASM\n", g_foot_addr);
    fprintf(ld, "   '-f bin' + 'org 0x%lx' produces directly for x86-64. */\n\n", g_foot_addr);

    fprintf(ld, "ENTRY(%s)\n\n", entry_label);
    fprintf(ld, "SECTIONS\n");
    fprintf(ld, "{\n");
    fprintf(ld, "    . = 0x%lx;\n\n", g_foot_addr);
    /* Section order mirrors exactly what emit__aarch64/emit__riscv
       already write into the .s file, top to bottom (.data, .bss,
       .text -- see either backend's own emit_* function) -- so the
       linked layout matches the source layout the programmer is
       actually looking at, rather than silently reordering things
       (e.g. the conventional .text-first ordering many linker scripts
       use) in a way that would make g_foot_addr no longer point at
       what the programmer expects to be there first. */
    fprintf(ld, "    .data : { *(.data) }\n");
    fprintf(ld, "    .bss  : { *(.bss) }\n");
    fprintf(ld, "    .text : { *(.text) }\n");
    fprintf(ld, "}\n");

    fclose(ld);
}

void check_bare_mode_requirements(target_t target) {
    (void)target; /* no longer used to gate '| foot' -- kept as a parameter
                      since main() already has it in hand at the call site
                      and a future backend-specific requirement might need
                      it again; see git history if that never materializes
                      and this should just be dropped. */
    if (g_mode == MODE_BARE && !g_foot_seen)
        fail("'| mode bare;' (the default -- add '| mode elf;' if that's not what you want) requires '| foot ADDR;' -- a flat/raw binary needs a chosen load address, there is no linker to place it for you");
    if (g_foot_seen && g_mode != MODE_BARE)
        fail("'| foot' has no effect under '| mode elf;' -- ELF mode's entry point is placed by the linker, not by a fixed address");
}

int main(int argc, char **argv) {
    const char *input_path = NULL;
    const char *output_path = NULL;
    char *derived_output_path = NULL;
    target_t target = TARGET_X86_64;
    int target_set = 0;

    for (int i = 1; i < argc; i++) {
        if (strncmp(argv[i], "-target=", 8) == 0) {
            const char *v = argv[i] + 8;
            if (strcmp(v, "x86-64") == 0) target = TARGET_X86_64;
            else if (strcmp(v, "aarch64") == 0 || strcmp(v, "arm64") == 0) target = TARGET_AARCH64;
            else if (strcmp(v, "riscv") == 0) target = TARGET_RISCV;
            else { fprintf(stderr, "unknown target: %s\n", v); return 1; }
            target_set = 1;
        } else if (strcmp(argv[i], "-c") == 0 && i + 1 < argc) {
            input_path = argv[++i];
        } else if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
            output_path = argv[++i];
        } else {
            fprintf(stderr, "unknown argument: %s\n", argv[i]);
            usage(argv[0]);
            return 1;
        }
    }

    if (!input_path) {
        usage(argv[0]);
        return 1;
    }

    /* .chh/.chd are meant to be pulled in via | include/| data, not
       compiled directly -- a header has no @entry block by convention,
       so -c'ing one directly is almost always a mistake. Warn, don't
       fail: nothing in the grammar actually requires this, and a
       weird-but-valid header-with-an-entry-block file should still be
       compilable if someone really wants that. */
    if (has_extension(input_path, ".chh") || has_extension(input_path, ".chd")) {
        fprintf(stderr,
            "warning: '%s' looks like a header/data file meant for '| include'/'| data', "
            "not direct compilation via -c\n", input_path);
    }

    if (!target_set) target = detect_native_target();
    g_target = target; /* must be set before parse__file() -- see
                           syscall_num_for_name */

    if (!output_path) {
        derived_output_path = derive_output_path(input_path);
        output_path = derived_output_path;
    }

    g_filename = intern_filename(input_path);
    mark_included(g_filename); /* so a | include/| data cycle that loops
                                   back around to the top-level file
                                   itself is caught the same way any
                                   other cycle is, instead of silently
                                   re-reading it */
    include_push(g_filename);
    FILE *in = fopen(input_path, "r");
    if (!in) { perror("fopen input"); return 1; }
    parse__file(in);
    fclose(in);
    include_pop();

    check_init_scratch_collision();
    splice_global_pin_loads();
    check_global_pin_violations();
    check_argv_pin_collision();
    check_addr_of_violations();
    apply_entry_symbol_override();
    check_bare_mode_requirements(target);

    FILE *out = fopen(output_path, "w");
    if (!out) { perror("fopen output"); return 1; }

    switch (target) {
        case TARGET_X86_64:  emit_x86_64(out);  break;
        case TARGET_AARCH64: emit__aarch64(out); break;
        case TARGET_RISCV:   emit__riscv(out);   break;
    }

    fclose(out);

    /* AArch64/RISC-V BARE-mode '| foot' needs a sibling linker script --
       see write_bare_mode_linker_script's comment for why (GAS, unlike
       NASM, has no source-level way to place code at a fixed address).
       x86-64 needs no such file: its 'org' directive is emitted
       straight into the .s output above (see emit_x86_64's OP_LABEL
       case), so this stays a genuine one-file-out build for that
       target, same as it always was. */
    char *ld_script_path = NULL;
    if (g_mode == MODE_BARE && g_foot_seen && target != TARGET_X86_64) {
        ld_script_path = derive_ld_script_path(output_path);
        write_bare_mode_linker_script(ld_script_path);
        fprintf(stderr, "note: wrote linker script '%s' -- '| foot' on this target needs "
                         "'ld -T %s' at link time (see the top of that file for the full "
                         "build command)\n", ld_script_path, ld_script_path);
    }

    /* One or more 'extern name(n) lib "libname";' declarations tagged a
       symbol as living in a real third-party C library (as opposed to
       plain libc, which every libc-linked build already gets for free).
       Chard stays text-out only (see the file banner comment) -- it
       doesn't invoke an assembler or linker itself -- so, exactly like
       the BARE-mode '| foot' linker-script note just above, the most it
       can do is tell the programmer the '-l' flags their own assemble+
       link command now needs. Printed once, listing every distinct
       tagged lib in first-seen declaration order (see note_extern_lib). */
    if (g_n_extern_libs > 0) {
        fprintf(stderr, "note: this program uses extern symbols from %d librar%s beyond libc -- "
                         "link with:", g_n_extern_libs, g_n_extern_libs == 1 ? "y" : "ies");
        for (int i = 0; i < g_n_extern_libs; i++) fprintf(stderr, " -l%s", g_extern_libs[i]);
        fprintf(stderr, "\n");
    }

    free(ld_script_path);
    free(derived_output_path);
    return 0;
}

